### ISSUE TITLE
Not seeing lint marks on mini map

### ISSUE THREAD

**Issue by dander401** [AtomLinter/atom-minimap-linter#5] opened 2015-08-23 21:59 UTC
<img width="1543" alt="screen shot 2015-08-23 at 5 57 24 pm" src="https://cloud.githubusercontent.com/assets/4235673/9430370/7339f1f2-49c0-11e5-8183-7afafb1e4ac4.png">

the bottom of the image displays the error the lint error for the line. The mini map does not show the red mark though

**Comment by Oh-Petya** [comment] 2015-11-18 17:15
I'm having the same issue.

**Comment by nesukun** [comment] 2015-11-19 00:23
Will try to take a look at this soon, it's still working for me somehow. Will try to repro it in a clean env

**Comment by nesukun** [comment] 2015-12-23 12:35
I've updated the package with some changes I've had in the backburner for... too long. Could all of you try with the updated package and report if this is still an issue?

**Comment by nesukun** [comment] 2016-01-05 18:05
Seems to be a duplicate of #4. reopen otherwise.

**Closed by nesukun** 2016-01-05 18:05 UTC
Labels: duplicate
