### ISSUE TITLE
Highligh does not work?

### ISSUE THREAD

**Issue by csholmq** [AtomLinter/atom-minimap-linter#4] opened 2015-08-06 14:51 UTC
I only managed to get _Marker Type: Line_ visibly working. Not sure if the others are broken or just unintuive.

Great plugin btw!

**Comment by nesukun** [comment] 2015-08-07 09:37
I currently use highlight-over myself, but there's been quite a few changes recently in Linter so I'll have a look at this ASAP. Have you tried re-saving or restarting atom after the setting change? Might just be a config sync problem.
![highlight-over](http://i.imgur.com/mAiNS4I.png)

**Comment by csholmq** [comment] 2015-08-07 11:36
Yes, but to no avail. I tried disabling the other minimap packages to make sure they don't interfere. Currently using linter-gcc btw.

**Comment by ttsirkia** [comment] 2015-11-03 10:33
+1, only line marker works

**Comment by nesukun** [comment] 2015-12-23 12:35
I've updated the package with some changes I've had in the backburner for... too long. Could all of you try with the updated package and report if this is still an issue?

**Comment by grawlinson** [comment] 2016-01-03 01:03
I've just performed a clean install of Atom + a few packages. Let me know if you want the entire list of packages.

I can get `marker type: line` working, but the others either do not work or only display the first error.

**Comment by nesukun** [comment] 2016-01-04 09:40
![image](https://cloud.githubusercontent.com/assets/288427/12087007/07976752-b2c7-11e5-961f-9701cf50965e.png)
Could you post a similar gif to this one and/or the relevant parts of your atom config file? I think this could be specific to certain linters.

**Comment by nesukun** [comment] 2016-01-04 10:28
Please take into account that highlight options only cover the marker's witdh, which might just be too thin to be seen on the minimap (jshint markers are sometimes one character long). The line marker type covers the full width, Which makes them visible in most situationns

**Comment by grawlinson** [comment] 2016-01-04 19:55
The bug seems to have disappeared, and the package now performs exactly as intended. Not quite sure what caused this to happen, but here's my Atom [config](https://gist.github.com/grawlinson/f7b1eb7bfe11f65ed59b) if required.

**Comment by nesukun** [comment] 2016-01-05 18:04
Will close this for now. If anyone thinks this is still not resolved please feel free to reopen this

**Comment by csholmq** [comment] 2016-01-05 18:37
Still present on Win7. Atom 1.3.2, minimap-linter 1.1.0. I'm using linter-gcc.

**Comment by csholmq** [comment] 2016-01-05 18:44
I might have to take back that last comment. If I select *highlight-outline* I do see a *small small small* red marking on the corresponding line. I guess I expected more to be highlighted in the different modes (except line, which does what I expected).

**Closed** 2016-01-06 00:14 UTC
Labels: bug
